name: Workflow

on:
  push:
    tags:
      - 'DEV'
    branches: ["main"]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
